### ISSUE TITLE
Verify Email Domain exist or not

### ISSUE THREAD

**Issue by nagarjuna1304** [GovindaPaliwal/Aadhaar-Offline-KYC-Android-Library#3]
Hi GovindaPaliwal,

Onemore request from me, is there any chance to verify email domain is exist or not? if exist Can we achieve through java code.?
Can you please suggest me if any.

Example :
xxxxx@diffcheck.com    --> verify 'diffcheck.com' is exist or not
xxxxx@accenture.co.in  --> verify 'accenture.co.in' is exist or not
xxxxx@wipro.co.in      --> verify 'wipro.co.in' is exist or not
xxxxx@tcs.in           --> verify 'tcs.in' is exist or not

Thanks in advance.

**Comment by GovindaPaliwal** [comment]
Sorry i don't know more about this. But for this you can check https://stackoverflow.com/questions/13514005/how-to-check-mail-address-is-exists-or-not this link. i think this is helpful.

**Comment by nagarjuna1304** [comment]
Thanks for provided useful link
